### ISSUE TITLE
[Feat] 프론트엔드 개발(Todo)

### ISSUE THREAD

**Issue by GraceKim527** [LikeLion-11th-SKHU/2023_SKHU_WorkShop#1]
- [x] : 전체적으로 모바일 웹으로 구현
- [x] : JS로 질문응답 받기
- [x] : 결과 별 항목 모두 다르게 하기
- [x] : UX 기준은 모두 "Mobile"
- [x] : 방명록 페이지 개발
- [x] : 소프트웨어 워크샵 소개 페이지 개발
- [x] : 소개 페이지 개발
